process.env.NODE_ENV='test';
process.env.SESSION_SECRET='SESSION_SECRET';

process.env.ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET';
process.env.REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET';

process.env.ENCRYPTION_ALGORITHM='aes-256-cbc';
process.env.ENCRYPTION_KEY = 'ENCRYPTION_KEY';
